### ISSUE TITLE
Add contents of hosts file if modified

### ISSUE THREAD

**Issue by Boxersteavee** [PipeItToDevNull/Get-Specs#71] opened 2022-05-05 20:42 UTC
There's a few times when I see that the hosts file is modified but I feel it would be much nicer to know what in it was modified, weather the user changed something or if malware had changed it (like Minecraft alt generators do to steal accounts)

**Comment by PipeItToDevNull** [comment] 2022-05-05 22:18
Duplicate of #65

**Closed by PipeItToDevNull** 2022-05-05 22:18 UTC
